import { Analysis } from 'src/analyses/interfaces/analysis.interface';

export const analysisStub = (): Analysis => {
  return {
    teams: [
      {
        teamId: 100,
        win: false,
        totalKills: 40,
        totalAssists: 69,
        totalDeaths: 63,
        totalDamageDone: 129389,
        totalDamageTaken: 187081,
        totalHealed: 27555,
        avgKP: 21.8,
        avgDeaths: 12.6,
        avgDamageDone: 25877.8,
        avgDamageTaken: 37416.2,
        avgHealed: 5511,
      },
      {
        teamId: 200,
        win: true,
        totalKills: 63,
        totalAssists: 161,
        totalDeaths: 40,
        totalDamageDone: 176918,
        totalDamageTaken: 137893,
        totalHealed: 50460,
        avgKP: 44.8,
        avgDeaths: 8,
        avgDamageDone: 35383.6,
        avgDamageTaken: 27578.6,
        avgHealed: 10092,
      },
    ],
    players: [
      {
        summonerName: 'ItsNexty',
        championId: 96,
        champion: 'KogMaw',
        teamId: 100,
        kills: 7,
        deaths: 12,
        assists: 13,
        KP: 20,
        damageDone: 28254,
        damageTaken: 27709,
        healed: 1642,
        doubleKills: 1,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 14782,
        goldSpent: 15370,
        totalMinionsKilled: 35,
        firstBloodKill: false,
        firstBloodAssist: false,
        longestTimeSpentLiving: 231,
        teamComparedKP: -0.08,
        teamComparedDeaths: -0.05,
        teamComparedDamageDone: 0.09,
        teamComparedDamageTaken: -0.26,
        teamComparedHealed: -0.7,
        KPGain: -1.6,
        deathsGain: 0.5,
        damageDoneGain: 0.9,
        damageTakenGain: -2.6,
        healedGain: -4,
        lpGain: -10.2,
        leaguePoints: -10.2,
      },
      {
        summonerName: 'ItsWolfy',
        championId: 92,
        champion: 'Riven',
        teamId: 100,
        kills: 11,
        deaths: 13,
        assists: 9,
        KP: 20,
        damageDone: 16879,
        damageTaken: 46367,
        healed: 7917,
        doubleKills: 2,
        tripleKills: 1,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 16137,
        goldSpent: 16800,
        totalMinionsKilled: 44,
        firstBloodKill: false,
        firstBloodAssist: false,
        longestTimeSpentLiving: 371,
        teamComparedKP: -0.08,
        teamComparedDeaths: 0.03,
        teamComparedDamageDone: -0.35,
        teamComparedDamageTaken: 0.24,
        teamComparedHealed: 0.44,
        KPGain: -1.6,
        deathsGain: -0.3,
        damageDoneGain: -3.5,
        damageTakenGain: 2.4,
        healedGain: 4,
        lpGain: -7.9,
        leaguePoints: -7.9,
      },
      {
        summonerName: 'UOL Doberdo',
        championId: 82,
        champion: 'Mordekaiser',
        teamId: 100,
        kills: 6,
        deaths: 14,
        assists: 9,
        KP: 15,
        damageDone: 20575,
        damageTaken: 48148,
        healed: 7899,
        doubleKills: 0,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 14981,
        goldSpent: 14150,
        totalMinionsKilled: 36,
        firstBloodKill: false,
        firstBloodAssist: false,
        longestTimeSpentLiving: 233,
        teamComparedKP: -0.31,
        teamComparedDeaths: 0.11,
        teamComparedDamageDone: -0.2,
        teamComparedDamageTaken: 0.29,
        teamComparedHealed: 0.43,
      },
      {
        summonerName: 'Baron Samedi',
        championId: 102,
        champion: 'Shyvana',
        teamId: 100,
        kills: 8,
        deaths: 12,
        assists: 16,
        KP: 24,
        damageDone: 33380,
        damageTaken: 33366,
        healed: 2834,
        doubleKills: 1,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 16548,
        goldSpent: 14450,
        totalMinionsKilled: 58,
        firstBloodKill: false,
        firstBloodAssist: false,
        longestTimeSpentLiving: 159,
        teamComparedKP: 0.1,
        teamComparedDeaths: -0.05,
        teamComparedDamageDone: 0.29,
        teamComparedDamageTaken: -0.11,
        teamComparedHealed: -0.49,
      },
      {
        summonerName: 'AcursedGoat',
        championId: 15,
        champion: 'Sivir',
        teamId: 100,
        kills: 8,
        deaths: 12,
        assists: 22,
        KP: 30,
        damageDone: 30301,
        damageTaken: 31491,
        healed: 7263,
        doubleKills: 0,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 18776,
        goldSpent: 18300,
        totalMinionsKilled: 141,
        firstBloodKill: false,
        firstBloodAssist: false,
        longestTimeSpentLiving: 239,
        teamComparedKP: 0.38,
        teamComparedDeaths: -0.05,
        teamComparedDamageDone: 0.17,
        teamComparedDamageTaken: -0.16,
        teamComparedHealed: 0.32,
      },
      {
        summonerName: 'Emyliah',
        championId: 104,
        champion: 'Graves',
        teamId: 200,
        kills: 13,
        deaths: 11,
        assists: 19,
        KP: 32,
        damageDone: 42127,
        damageTaken: 34327,
        healed: 5144,
        doubleKills: 2,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 17535,
        goldSpent: 16400,
        totalMinionsKilled: 106,
        firstBloodKill: false,
        firstBloodAssist: true,
        longestTimeSpentLiving: 241,
        teamComparedKP: -0.29,
        teamComparedDeaths: 0.38,
        teamComparedDamageDone: 0.19,
        teamComparedDamageTaken: 0.24,
        teamComparedHealed: -0.49,
      },
      {
        summonerName: 'Thaeron',
        championId: 202,
        champion: 'Jhin',
        teamId: 200,
        kills: 33,
        deaths: 9,
        assists: 16,
        KP: 49,
        damageDone: 57815,
        damageTaken: 38237,
        healed: 12340,
        doubleKills: 8,
        tripleKills: 2,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 21651,
        goldSpent: 21150,
        totalMinionsKilled: 105,
        firstBloodKill: false,
        firstBloodAssist: true,
        longestTimeSpentLiving: 243,
        teamComparedKP: 0.09,
        teamComparedDeaths: 0.13,
        teamComparedDamageDone: 0.63,
        teamComparedDamageTaken: 0.39,
        teamComparedHealed: 0.22,
      },
      {
        summonerName: 'First Love',
        championId: 267,
        champion: 'Nami',
        teamId: 200,
        kills: 0,
        deaths: 6,
        assists: 52,
        KP: 52,
        damageDone: 7980,
        damageTaken: 21867,
        healed: 13882,
        doubleKills: 0,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 14940,
        goldSpent: 13950,
        totalMinionsKilled: 12,
        firstBloodKill: false,
        firstBloodAssist: true,
        longestTimeSpentLiving: 594,
        teamComparedKP: 0.16,
        teamComparedDeaths: -0.25,
        teamComparedDamageDone: -0.77,
        teamComparedDamageTaken: -0.21,
        teamComparedHealed: 0.38,
      },
      {
        summonerName: '9th February',
        championId: 350,
        champion: 'Yuumi',
        teamId: 200,
        kills: 3,
        deaths: 5,
        assists: 46,
        KP: 49,
        damageDone: 17014,
        damageTaken: 13900,
        healed: 9738,
        doubleKills: 0,
        tripleKills: 0,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 15329,
        goldSpent: 16380,
        totalMinionsKilled: 7,
        firstBloodKill: false,
        firstBloodAssist: true,
        longestTimeSpentLiving: 434,
        teamComparedKP: 0.09,
        teamComparedDeaths: -0.38,
        teamComparedDamageDone: -0.52,
        teamComparedDamageTaken: -0.5,
        teamComparedHealed: -0.04,
      },
      {
        summonerName: 'Knudseren',
        championId: 142,
        champion: 'Zoe',
        teamId: 200,
        kills: 14,
        deaths: 9,
        assists: 28,
        KP: 42,
        damageDone: 51982,
        damageTaken: 29562,
        healed: 9356,
        doubleKills: 2,
        tripleKills: 1,
        quadraKills: 0,
        pentaKills: 0,
        goldEarned: 17874,
        goldSpent: 13650,
        totalMinionsKilled: 63,
        firstBloodKill: true,
        firstBloodAssist: false,
        longestTimeSpentLiving: 322,
        teamComparedKP: -0.06,
        teamComparedDeaths: 0.13,
        teamComparedDamageDone: 0.47,
        teamComparedDamageTaken: 0.07,
        teamComparedHealed: -0.07,
      },
    ],
    game: {
      gameDuration: 1565466,
      gameCreation: 1629673245000,
      queueId: 450,
      gameId: 5426644723,
    },
  };
};
