import { Player } from 'src/stats/schemas/player.schemas';

/**
 * Note: these stats are purely fictional, unrealistic and sometimes disproportional, on purpose. They are only to be used when simulating leaderboards.
 */
export const leaderboardPlayerStatsStub = (): Player[] => {
  return [
    {
      discordId: '227833554258624523',
      rankedGames: 10,
      wins: 6,
      leaguePoints: 100,
      pointsWon: 80,
      pentaKills: 2,
      deaths: 20,
      healed: 0,
      damageTaken: 0,
      damageDealt: 0,
      quadraKills: 0,
      tripleKills: 0,
      doubleKills: 0,
      firstBloodAssists: 0,
      firstBloods: 0,
      assists: 400,
      kills: 0,
      goldSpent: 0,
      goldEarned: 0,
      pointsLost: 0,
    },
    {
      discordId: '228176803523461121',
      rankedGames: 10,
      wins: 7,
      leaguePoints: 80,
      pointsWon: 126,
      pentaKills: 5,
      deaths: 18,
      healed: 0,
      damageTaken: 0,
      damageDealt: 0,
      quadraKills: 0,
      tripleKills: 0,
      doubleKills: 0,
      firstBloodAssists: 0,
      firstBloods: 0,
      assists: 414,
      kills: 0,
      goldSpent: 0,
      goldEarned: 0,
      pointsLost: 0,
    },
    {
      discordId: '234019478495559681',
      rankedGames: 10,
      wins: 8,
      leaguePoints: 90,
      pointsWon: 136,
      pentaKills: 3,
      deaths: 16,
      healed: 0,
      damageTaken: 0,
      damageDealt: 0,
      quadraKills: 0,
      tripleKills: 0,
      doubleKills: 0,
      firstBloodAssists: 0,
      firstBloods: 0,
      assists: 528,
      kills: 0,
      goldSpent: 0,
      goldEarned: 0,
      pointsLost: 0,
    },
    {
      discordId: '111111111111111111',
      rankedGames: 10,
      wins: 10,
      leaguePoints: 70,
      pointsWon: 160,
      pentaKills: 0,
      deaths: 25,
      healed: 0,
      damageTaken: 0,
      damageDealt: 0,
      quadraKills: 0,
      tripleKills: 0,
      doubleKills: 0,
      firstBloodAssists: 0,
      firstBloods: 0,
      assists: 600,
      kills: 0,
      goldSpent: 0,
      goldEarned: 0,
      pointsLost: 0,
    },
    {
      discordId: '22222222222222222',
      rankedGames: 10,
      wins: 4,
      leaguePoints: 60,
      pointsWon: 48,
      pentaKills: 0,
      deaths: 28,
      healed: 0,
      damageTaken: 0,
      damageDealt: 0,
      quadraKills: 0,
      tripleKills: 0,
      doubleKills: 0,
      firstBloodAssists: 0,
      firstBloods: 0,
      assists: 532,
      kills: 0,
      goldSpent: 0,
      goldEarned: 0,
      pointsLost: 0,
    },
    {
      discordId: '33333333333333333',
      rankedGames: 10,
      wins: 5,
      leaguePoints: 50,
      pointsWon: 95,
      pentaKills: 1,
      deaths: 15,
      healed: 0,
      damageTaken: 0,
      damageDealt: 0,
      quadraKills: 0,
      tripleKills: 0,
      doubleKills: 0,
      firstBloodAssists: 0,
      firstBloods: 0,
      assists: 330,
      kills: 0,
      goldSpent: 0,
      goldEarned: 0,
      pointsLost: 0,
    },
  ];
};
